// Code generated by "stringer -type=Field,FieldName -output=constant_string.go"; DO NOT EDIT.

package address

import "strconv"

const _Field_name = "CountryNameOrganizationStreetAddressDependentLocalityLocalityAdministrativeAreaPostCodeSortingCode"

var _Field_index = [...]uint8{0, 7, 11, 23, 36, 53, 61, 79, 87, 98}

func (i Field) String() string {
	i -= 1
	if i < 0 || i >= Field(len(_Field_index)-1) {
		return "Field(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Field_name[_Field_index[i]:_Field_index[i+1]]
}

const _FieldName_name = "AreaCityCountyDepartmentDistrictDoSiEircodeEmirateIslandNeighborhoodOblastPINCodeParishPostTownPostalCodePrefectureProvinceStateSuburbTownlandVillageTownshipZipCode"

var _FieldName_index = [...]uint8{0, 4, 8, 14, 24, 32, 36, 43, 50, 56, 68, 74, 81, 87, 95, 105, 115, 123, 128, 134, 142, 157, 164}

func (i FieldName) String() string {
	i -= 1
	if i < 0 || i >= FieldName(len(_FieldName_index)-1) {
		return "FieldName(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FieldName_name[_FieldName_index[i]:_FieldName_index[i+1]]
}
