on:
  schedule:
    - cron: '0 0 * * *'
name: Update Generated Data
jobs:
  update-generated-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.BOOSTPORT_AUTOMATION_APP_ID }}
          private_key: ${{ secrets.BOOSTPORT_AUTOMATION_APP_PRIVATE_KEY }}
      - name: Generate data
        run: docker compose run generate
      - name: Open PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update-generated-data
          author: GitHub <noreply@github.com>
          committer: GitHub <noreply@github.com>
          commit-message: Update generated data
          title: 'Update generated data'
          body: |
            Automated update for `data.generated.go`
          labels: automated pr
          team-reviewers: open-source
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}