on:
  schedule:
    - cron: '0 0 * * *'
name: Update Generated Data
jobs:
  update-generated-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate data
        run: docker compose run generate
      - name: Diff generated file
        shell: bash {0}
        run: |
          git diff --exit-code --quiet data.generated.go
          echo "HAS_CHANGES=$?" >> $GITHUB_ENV
          exit 0
      - name: Open PR
        uses: peter-evans/create-pull-request@v4
        if: env.HAS_CHANGES == '1'
        with:
          branch: update-generated-data
          commit-message: Update generated data
          title: 'Update generated data'
          body: |
            Automated update for `data.generated.go`
          labels: automated pr
          reviewers: F21