on:
  schedule:
    - cron: '0 0 * * *'
name: Update Generated Data
jobs:
  update-generated-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate data
        run: docker compose run generate
      - name: Open PR
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update-generated-data
          author: GitHub <noreply@github.com>
          committer: GitHub <noreply@github.com>
          commit-message: Update generated data
          title: 'Update generated data'
          body: |
            Automated update for `data.generated.go`
          labels: automated pr
          reviewers: F21